PizzaPalaceWeb.solution/PizzaPalaceWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PizzaPalaceWeb.Models;

namespace PizzaPalaceWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PizzaPalaceWeb.solution/PizzaPalaceWeb/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using PizzaPalace.Data;
using PizzaPalace.Library;
using PizzaPalaceWeb.Models;

namespace PizzaPalaceWeb.Controllers
{
    public class OrdersController : Controller
    {
        private readonly PizzaPalacedbContext _context;
        public SelectListItem SelectedSize { get; set; }
        public UserRepository Repo { get; }
        public int Count = 0;
        public int Total = 0;
        public List<int> toppins = new List<int>();

        public OrdersController(PizzaPalacedbContext context, UserRepository repo)
        {
            _context = context;
            Repo = repo;
        }

        public IActionResult ShowOrder()
        {
            return View();
        }

        //Get: placeAnOrder
        public IActionResult OrderSubmit()
        {
            //PizzaM pizza = new PizzaM();
            //OrderM order = new OrderM();
            //OrdersPizzaModel orderPizza = new OrdersPizzaModel();

            return View();
        }

        // Post: PlaceAnOrder
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult OrderSubmit(IFormCollection VC, Users user)
        {

            int UseridTD = int.Parse(TempData.Peek("userid").ToString());
            int LocationTD = int.Parse(TempData.Peek("locationid").ToString());
            string NameTD = TempData.Peek("firstname").ToString();
            string LastnameTD = TempData.Peek("lastname").ToString();
            string PhoneTD = TempData.Peek("phone").ToString();

            if (Count == 12)
            {
                ViewData["msg"] = "You can't order more than 12 Pizzas :( ";
                return RedirectToAction(nameof(OrderSubmit));
            }

            string SelectedPizza = VC["SP"];
            int SelectedSize = int.Parse(VC["SS"]);
            //ModeloGeneral myModel = new ModeloGeneral();
            double cost;
            double ELTOTAL;
            //pizza.Pizza1 = myModel.SelectTopping.Value;
            //pizza.Size = myModel.SelectSize.Value;

            //// Sets the values
            //order.OrderId = user.Id;
            //order.LocationsIdfk = user.DefaultLocationFk;
            //pizza.Cost = Total;

            if (SelectedSize == 1)
            {
                cost = 6;

                ELTOTAL = int.Parse(TempData.Peek("order_total").ToString());
                ELTOTAL += 6;
                TempData["order_total"] = ELTOTAL;
            }
            else if (SelectedSize == 2)
            {
                cost = 12;
                ELTOTAL = int.Parse(TempData.Peek("order_total").ToString());
                ELTOTAL += 12;
                TempData["order_total"] = ELTOTAL;

            }
            else
            {
                cost = 17;
                ELTOTAL = int.Parse(TempData.Peek("order_total").ToString());
                ELTOTAL += 17;
                TempData["order_total"] = ELTOTAL;

            }


            //check availability of ingredients for each pizza
            bool availability = Repo.checkInv(LocationTD);
            
            if (availability == true)
            {
                // take out toppings from db

                //add pizza
                
                if (TempData.Peek("Count").ToString() == "1")
                {
                    Count = 1;

                }
                else
                {
                    Count = int.Parse(TempData.Peek("Count").ToString());
                }


                if (Count < 2)//only if the order is new is going to be created
                {
                    Repo.SubmitOrder(UseridTD, LocationTD);

                    /////////////////////////////////////////////////////////////////////////////Repo.SubmitOrder(UseridTD, LocationTD, Order_total);

                }
                int? OrderIDs = Repo.GetOrderByUserId(UseridTD);

                //increment counter to know next time, that this is not a new order.
                if (SelectedPizza == "Cheese")
                {
                    Repo.Cheesepizza(SelectedSize, LocationTD, cost, SelectedPizza, UseridTD);
                }
                if (SelectedPizza == "Pepperoni")
                {
                    Repo.Pepperoni(SelectedSize, LocationTD, cost, SelectedPizza, UseridTD);
                }
                if (SelectedPizza == "Allmeat")
                {
                    Repo.AllMeat(SelectedSize, LocationTD, cost, SelectedPizza, UseridTD);
                }
                if (SelectedPizza == "Chorizo")
                {
                    Repo.Chorizo(SelectedSize, LocationTD, cost, SelectedPizza, UseridTD);
                }
                if (SelectedPizza == "Bacon")
                {
                    Repo.Bacon(SelectedSize, LocationTD, cost, SelectedPizza, UseridTD);
                }
                Repo.SaveChanges();
                Count++;
                TempData["Count"] = Count;
                return RedirectToAction(nameof(OrderSubmit));
                
            }
            else
            {
                ViewData["msg"] = "Not enough reseources to complete your order, Please choose again...";
                return RedirectToAction(nameof(OrderSubmit));
            }


        }



        public ActionResult PizzaPalace(Orders order)
        {
            ////////////////////////////////////////////////////////////////////////////////////////
            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            IConfigurationRoot configuration = builder.Build();
            Console.WriteLine(configuration.GetConnectionString("PizzaPalacedb"));
            var optionsBuilder = new DbContextOptionsBuilder<PizzaPalacedbContext>();
            optionsBuilder.UseSqlServer(configuration.GetConnectionString("PizzaPalacedb"));
            ////////////////////////////////////////////////////////////////////////////////////////
            //var Loc = SelectedSize.Value;
            //var Location = Int32.Parse(Loc);

            var repo = new UserRepository(new PizzaPalacedbContext(optionsBuilder.Options));
            var LocationsSearch = Repo.GetLocation();// get all locat
            var location = LocationsSearch.FirstOrDefault(q => q.LocationsId == 1);// the location
            var won = Repo.GetOrdersTable(); // Get all Order
            var order2 = won.Where(q => q.LocationsIdfk == location.LocationsId); // order from loc


            //TempData["id"] = ELUSER.Id;
            //TempData["name"] = ELUSER.FirstName;
            //TempData["last"] = ELUSER.LastName;
            //TempData["phone"] = ELUSER.PhoneNumber;
            return View(order2);
        }




        public ActionResult Index(string sortOrder)
        {
            ViewBag.LocSortParm = String.IsNullOrEmpty(sortOrder) ? "Location_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date_desc" : "Date";
            //ViewBag.User = sortOrder == "User" ? "User" : "User_desc";
            var Oder = from s in Repo.GetOrdersTable()
                       select s;

            switch (sortOrder)
            {
                case "Date":
                    Oder = Oder.OrderBy(s => s.DateTimeOrder);
                    break;
                case "Date_desc":
                    Oder = Oder.OrderByDescending(s => s.DateTimeOrder);
                    break;
                //case "Location_desc":
                //    Oder = Oder.OrderByDescending(s => s.LocationsIdfk);
                //    break;
                //case "User":
                //    Oder = Oder.OrderBy(s => s.UserIdfk);
                //    break;
                //case "User_desc":
                //    Oder = Oder.OrderByDescending(s => s.UserIdfk);
                //    break;
                default:
                    Oder = Oder.OrderBy(s => s.LocationsIdfk);
                    break;

            }
            return View(Oder.ToList());

        }
        // GET: Orders
        //public async Task<IActionResult> Index()
        //{
        //    var pizzaPalacedbContext = _context.Orders.Include(o => o.LocationsIdfkNavigation).Include(o => o.UserIdfkNavigation);
        //    return View(await pizzaPalacedbContext.ToListAsync());
        //}

        //public IActionResult AngelitoOrder()
        //{
        //    return View();
        //}



        public ActionResult AngelitoOrder(Orders order)
        {
            ////////////////////////////////////////////////////////////////////////////////////////
            var builder = new ConfigurationBuilder()
            .SetBasePath(Directory.GetCurrentDirectory())
            .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true);
            IConfigurationRoot configuration = builder.Build();
            Console.WriteLine(configuration.GetConnectionString("PizzaPalacedb"));
            var optionsBuilder = new DbContextOptionsBuilder<PizzaPalacedbContext>();
            optionsBuilder.UseSqlServer(configuration.GetConnectionString("PizzaPalacedb"));
            ////////////////////////////////////////////////////////////////////////////////////////
            //var Loc = SelectedSize.Value;
            //var Location = Int32.Parse(Loc);

            var repo = new UserRepository(new PizzaPalacedbContext(optionsBuilder.Options));
            var LocationsSearch = Repo.GetLocation();// get all locat
            var location = LocationsSearch.FirstOrDefault(q => q.LocationsId == 2);// the location
            var won = Repo.GetOrdersTable(); // Get all Order

PizzaPalaceWeb.solution/PizzaPalaceWeb/Controllers/PizzasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PizzaPalace.Data;
using PizzaPalace.Library;

namespace PizzaPalaceWeb.Controllers
{
    public class PizzasController : Controller
    {
        private readonly PizzaPalacedbContext _context;
        public UserRepository Repo { get; }

        public PizzasController(PizzaPalacedbContext context, UserRepository repo)
        {
            _context = context;
            Repo = repo;
        }

        public ActionResult Index(string sortOrder)
        {
            //ViewBag.LocSortParm = String.IsNullOrEmpty(sortOrder) ? "Location_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Cost" ? "Cost_desc" : "Cost";
            ViewBag.Pizzas = sortOrder == "Pizza" ? "Pizza_desc" : "Pizza";
            var Oder = from s in Repo.GetPizza()
                       select s;

            switch (sortOrder)
            {
                case "Cost":
                    Oder = Oder.OrderBy(s => s.Cost);
                    break;
                case "Cost_desc":
                    Oder = Oder.OrderByDescending(s => s.Cost);
                    break;
                case "Pizza":
                    Oder = Oder.OrderBy(s => s.Pizza1);
                    break;
                case "Pizza_desc":
                    Oder = Oder.OrderByDescending(s => s.Pizza1);
                    break;
                default:
                    Oder = Oder.OrderBy(s => s.Cost);
                    break;

            }
            return View(Oder.ToList());

        }


        // GET: Pizzas
        //public async Task<IActionResult> Index()
        //{
        //    var pizzaPalacedbContext = _context.Pizza.Include(p => p.OrdersIdfkNavigation);
        //    return View(await pizzaPalacedbContext.ToListAsync());
        //}

        // GET: Pizzas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizza
                .Include(p => p.OrdersIdfkNavigation)
                .FirstOrDefaultAsync(m => m.PizzaId == id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // GET: Pizzas/Create
        public IActionResult Create()
        {
            ViewData["OrdersIdfk"] = new SelectList(_context.Orders, "OrderId", "OrderId");
            return View();
        }

        // POST: Pizzas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PizzaId,Pizza1,Size,Cost,OrdersIdfk,Doug,Cheese,Pepperoni,Sausage,Bacon,Onion,Chiken,Sauce,Chorizo")] Pizza pizza)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pizza);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrdersIdfk"] = new SelectList(_context.Orders, "OrderId", "OrderId", pizza.OrdersIdfk);
            return View(pizza);
        }

        // GET: Pizzas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizza.FindAsync(id);
            if (pizza == null)
            {
                return NotFound();
            }
            ViewData["OrdersIdfk"] = new SelectList(_context.Orders, "OrderId", "OrderId", pizza.OrdersIdfk);
            return View(pizza);
        }

        // POST: Pizzas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PizzaId,Pizza1,Size,Cost,OrdersIdfk,Doug,Cheese,Pepperoni,Sausage,Bacon,Onion,Chiken,Sauce,Chorizo")] Pizza pizza)
        {
            if (id != pizza.PizzaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pizza);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PizzaExists(pizza.PizzaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["OrdersIdfk"] = new SelectList(_context.Orders, "OrderId", "OrderId", pizza.OrdersIdfk);
            return View(pizza);
        }

        // GET: Pizzas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var pizza = await _context.Pizza
                .Include(p => p.OrdersIdfkNavigation)
                .FirstOrDefaultAsync(m => m.PizzaId == id);
            if (pizza == null)
            {
                return NotFound();
            }

            return View(pizza);
        }

        // POST: Pizzas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var pizza = await _context.Pizza.FindAsync(id);
            _context.Pizza.Remove(pizza);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PizzaExists(int id)
        {
            return _context.Pizza.Any(e => e.PizzaId == id);
        }
    }
}

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/Create.cshtml
@model PizzaPalace.Data.Users

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefaultLocationFk" class="control-label"></label>
                <select asp-for="DefaultLocationFk" class ="form-control" asp-items="ViewBag.DefaultLocationFk"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/Delete.cshtml
@model PizzaPalace.Data.Users

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DefaultLocationFkNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DefaultLocationFkNavigation.LocationsId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/Details.cshtml
@model PizzaPalace.Data.Users

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Users</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DefaultLocationFkNavigation)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DefaultLocationFkNavigation.LocationsId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/Edit.cshtml
@model PizzaPalace.Data.Users

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Users</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DefaultLocationFk" class="control-label"></label>
                <select asp-for="DefaultLocationFk" class="form-control" asp-items="ViewBag.DefaultLocationFk"></select>
                <span asp-validation-for="DefaultLocationFk" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/Home.cshtml
@model IEnumerable<PizzaPalace.Data.Users>

@{
    ViewData["Title"] = "Home";
}
<style>
    button {
        margin-top: 5px;
        margin-bottom: 5px;
        display: inline-block;
        *display: inline; 
        zoom: 1; 
        vertical-align: middle;
        margin-left: 20px;
        }

  h4 {
        display: inline-block;
        *display: inline; 
        zoom: 1;
        float: left;
        padding-top: 5px;
        text-align: left;
        width: 450px;
        }
    body {
        background-color: black;
    }


</style>
<body>
    <h1 align="center" style="color: white">Pizza Palace</h1>

    <table class="table" style="border: double; background-color: white">
        <thead>
            <tr>
                <th style="display: flex">
                    <div class="form-group">
                        <h4> Get Pizza</h4>
                        <button type="submit" class="btn btn-default "><a style="color: black" href="LogIN">SELECT</a></button>
                    </div>

                </th>
            </tr>
            <tr>
                <th>
                    <div class="form-group">
                        <h4> Search users by name</h4>
                        <button type="submit" class="btn btn-default "><a style="color: black" href="SearcUser">SELECT</a></button>
                    </div>

                </th>
            </tr>
            <tr>
                <th>
                    <h4> Display all order history of Angelitos Pizzeria</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" asp-area="" asp-controller="Orders" asp-action="AngelitoOrder">SELECT</a></button>
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <h4> Display all order history of Pizza Palace!</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" asp-area="" asp-controller="Orders" asp-action="PizzaPalace">SELECT</a></button>
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <h4> All Users</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" href="index">SELECT</a></button>
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <h4> All Locations and Inventory</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" asp-area="" asp-controller="Locations" asp-action="Index">SELECT</a></button>
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <h4> All Order</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" asp-area="" asp-controller="Orders" asp-action="Index">SELECT</a></button>
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <h4> All Pizzas</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" asp-area="" asp-controller="Pizzas" asp-action="Index">SELECT</a></button>
                    </div>
                </th>
            </tr>
            <tr>
                <th>
                    <h4> User/Order/Pizzas Relations</h4>
                    <div class="form-group">
                        <button type="submit" class="btn btn-default "><a style="color: black" asp-area="" asp-controller="PizzaOrder" asp-action="Index">SELECT</a></button>
                    </div>
                </th>
            </tr>
            @*<th>
            @Html.DisplayNameFor(model => model.DefaultLocationFkNavigation)
        </th>
        <th></th>*@
            </tr>
        </thead>
    </table>
</body>

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/Index.cshtml
@model IEnumerable<PizzaPalace.Data.Users>

@{
    ViewData["Title"] = "Index";
}

<h2>All User</h2>

<table class="table" style="border: dashed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DefaultLocationFk)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DefaultLocationFkNavigation.LocationsId)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |
            </td>
        </tr>
}
    </tbody>
</table>

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/LogIN.cshtml
@model PizzaPalaceWeb.Models.UsersModel

@{
    ViewData["Title"] = "LogIN";
}

<style>
    body {
        background-color: gainsboro;
    }
</style>


<h1 align="center">Welcome to Pizza Palace!</h1>
<hr />
<div class="row">

    <div class="col-md-4">
        <form   asp-action="LogIN">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden"  asp-for="Id" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" required="required" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" required="required" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" required="required" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <input type="submit" value="Save" class="btn btn-default" />

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PizzaPalaceWeb.solution/PizzaPalaceWeb/Views/Users/OrderLocation.cshtml
@*@model Orders
@using PizzaPalace.Data;
@{
    ViewData["Title"] = "OrderLocation";
}

<h2>OrderLocation</h2>
<table>
    <tr>
        <th>order Id</th>
        <th>Pizza</th>
        <th>User ID (FK)</th>
    </tr>
    @foreach (Orders item in Orders)
    {
        <tr>
            <td>@item.OrderId</td>
            <td>@item.Code</td>
            <td>@item.Name</td>
        </tr>
    }
</table>

<p><b>Student List</b></p>

<table>
    <tr>
        <th>Id</th>
        <th>Code</th>
        <th>Name</th>
        <th>Enrollment No</th>
    </tr>
    @foreach (Student student in Model.Students)
    {
        <tr>
            <td>@student.StudentId</td>
            <td>@student.Code</td>
            <td>@student.Name</td>
            <td>@student.EnrollmentNo</td>
        </tr>
    }
</table>*@  